# Resources settings
source:      .
layouts_dir:     ./_layouts
timezone:    +0800
plugins: ['jekyll-paginate']

# Site settings
email: andrew.petersen@utoronto.ca
author: Andrew Petersen
url: https://utmandrew.github.io/anonfeedback/

github: https://github.com/utmandrew/anonfeedback
baseurl: ""

future: true
show_drafts: nil
lsi: true
published: false
safe: false
permalink: /:year/:month/:day/:title/
paginate_path: /lang/page:num
paginate: 2
markdown: kramdown
excerpt_separator: '<!-- more -->'

exclude: ['README.md']

github_username: utmandrew
owner_name: Andrew

# Keywords
keywords:
        - "anonymous feedback"
        - "UTM"
        - "Toronto"
        - "Mathematical and Computational Sciences"
        
#Others
BaiduSiteVerification: "lLhmCmVmTf"
